create table Answers (Topic varchar(255), Question varchar(255), Answer varchar(255));
insert into Answers values ('time_signature', '1', '4_4');
insert into Answers values ('time_signature', '2', '7_4');
insert into Answers values ('time_signature', '3', '5_8');
insert into Answers values ('time_signature', '4', '3_4');
insert into Answers values ('time_signature', '5', '3_8');
insert into Answers values ('time_signature', '6', '7_8');
insert into Answers values ('time_signature', '7', '2_4');
insert into Answers values ('time_signature', '8', '3_4');
insert into Answers values ('time_signature', '9', '5_4');
insert into Answers values ('time_signature', '10', '6_4');
insert into Answers values ('time_signature', '11', '12_8');
insert into Answers values ('time_signature', '12', '9_8');
insert into Answers values ('time_signature', '13', '6_8');
insert into Answers values ('time_signature', '14', '9_4');
insert into Answers values ('time_signature', '15', '4_4');
insert into Answers values ('time_signature', '16', '3_4');
insert into Answers values ('time_signature', '17', '3_8');
insert into Answers values ('time_signature', '18', '6_8');
insert into Answers values ('time_signature', '19', '5_4');
insert into Answers values ('time_signature', '20', '4_4');
insert into Answers values ('time_signature', '21', '3_8');
insert into Answers values ('time_signature', '22', '5_8');
insert into Answers values ('time_signature', '23', '9_4');
insert into Answers values ('time_signature', '24', '6_4');
insert into Answers values ('rhythm', 'A breve is equal to ……… crotchet(s).', '8' );
insert into Answers values ('rhythm', 'In 6/8, there are ……… dotted-crotchet beats in a bar.', '2');
insert into Answers values ('rhythm', 'A crotchet is equal to ……… demisemiquaver(s).', '8');
insert into Answers values ('rhythm', 'A quaver triplet means three quavers in the time of ……… quaver(s).', '2');
insert into Answers values ('rhythm', 'In 3/4, there are ……… quaver beats in a bar.', '3');
insert into Answers values ('rhythm', 'A semibreve is equal to ……… quaver(s).', '4');
insert into Answers values ('rhythm', 'A quaver is equal to ……… demisemiquaver(s).', '4');
insert into Answers values ('rhythm', 'In 9/4, there are ……… dotted-minim beats in a bar.', '3');
insert into Answers values ('rhythm', 'In 12/16, there are ……… dotted-quaver beats in a bar.', '4');
insert into Answers values ('rhythm', 'A dotted minim is equal to ……… semiquaver(s).', '12');
insert into Answers values ('rhythm', 'A dotted semibreve is equal to ……… crotchet(s).', '6');
insert into Answers values ('rhythm', 'A quaver quintuplet means five quaver in the time of ……… crotchet(s). ', '4');
insert into Answers values ('rests_judgement', '1', 'OXO');
insert into Answers values ('rests_judgement', '2', 'XOO');
insert into Answers values ('rests_judgement', '3', 'XOO');
insert into Answers values ('rests_judgement', '4', 'XOO');
insert into Answers values ('rests_judgement', '5', 'OOX');
insert into Answers values ('rests_judgement', '6', 'XOO');
insert into Answers values ('rests_judgement', '7', 'OOO');
insert into Answers values ('rests_judgement', '8', 'OOX');
insert into Answers values ('rests_judgement', '9', 'XOO');
insert into Answers values ('rests_judgement', '10', 'OXX');
insert into Answers values ('rests_judgement', '11', 'XOO');
insert into Answers values ('rests_judgement', '12', 'OXX');
insert into Answers values ('note_naming', 'C,E,D,B,A', 'C');
insert into Answers values ('note_naming', 'D,F,E,C,B', 'D');
insert into Answers values ('note_naming', 'E,G,F,D,C', 'E');
insert into Answers values ('note_naming', 'F,A,G,E,D', 'F');
insert into Answers values ('note_naming', 'G,B,A,F,E', 'G');
insert into Answers values ('note_naming', 'A,C,B,G,F', 'A');
insert into Answers values ('note_naming', 'B,D,C,A,G', 'B');
insert into Answers values ('note_naming', 'Cb,Eb,Db,Bb,Ab', 'Cb');
insert into Answers values ('note_naming', 'Db,Fb,Eb,Cb,Bb', 'Db');
insert into Answers values ('note_naming', 'Eb,Gb,Fb,Db,Cb', 'Eb');
insert into Answers values ('note_naming', 'Fb,Ab,Gb,Eb,Db', 'Fb');
insert into Answers values ('note_naming', 'Gb,Bb,Ab,Fb,Eb', 'Gb');
insert into Answers values ('note_naming', 'Ab,Cb,Bb,Gb,Fb', 'Ab');
insert into Answers values ('note_naming', 'Bb,Db,Cb,Ab,Gb', 'Bb');
insert into Answers values ('note_naming', 'C#,E#,D#,B#,A#', 'C#');
insert into Answers values ('note_naming', 'D#,F#,E#,C#,B#', 'D#');
insert into Answers values ('note_naming', 'E#,G#,F#,D#,C#', 'E#');
insert into Answers values ('note_naming', 'F#,A#,G#,E#,D#', 'F#');
insert into Answers values ('note_naming', 'G#,B#,A#,F#,E#', 'G#');
insert into Answers values ('note_naming', 'A#,C#,B#,G#,F#', 'A#');
insert into Answers values ('note_naming', 'B#,D#,C#,A#,G#', 'B#');
insert into Answers values ('note_naming', 'C##,E##,D##,B##,A##', 'C##');
insert into Answers values ('note_naming', 'D##,F##,E##,C##,B##', 'D##');
insert into Answers values ('note_naming', 'E##,G##,F##,D##,C##', 'E##');
insert into Answers values ('note_naming', 'F##,A##,G##,E##,D##', 'F##');
insert into Answers values ('note_naming', 'G##,B##,A##,F##,E##', 'G##');
insert into Answers values ('note_naming', 'A##,C##,B##,G##,F##', 'A##');
insert into Answers values ('note_naming', 'B##,D##,C##,A##,G##', 'B##');
insert into Answers values ('note_naming', 'Cbb,Ebb,Dbb,Bbb,Abb', 'Cbb');
insert into Answers values ('note_naming', 'Dbb,Fbb,Ebb,Cbb,Bbb', 'Dbb');
insert into Answers values ('note_naming', 'Ebb,Gbb,Fbb,Dbb,Cbb', 'Ebb');
insert into Answers values ('note_naming', 'Fbb,Abb,Gbb,Ebb,Dbb', 'Fbb');
insert into Answers values ('note_naming', 'Gbb,Bbb,Abb,Fbb,Ebb', 'Gbb');
insert into Answers values ('note_naming', 'Abb,Cbb,Bbb,Gbb,Fbb', 'Abb');
insert into Answers values ('note_naming', 'Bbb,Dbb,Cbb,Abb,Gbb', 'Bbb');
create table answer_transposition (question int, transposition varchar(255), answer varchar(255));
insert into answer_transposition values (1, 'up a major 2nd', 'OXOXX');
insert into answer_transposition values (2, 'down a major 3rd', 'XXOXO');
insert into answer_transposition values (3, 'down a major 3rd', 'OOXOX');
insert into answer_transposition values (4, 'up a major 2nd', 'XXOXO');
insert into answer_transposition values (5, 'up a major 2nd','OOXXO');
insert into answer_transposition values (6, 'up a perfect 5th', 'XOXXO');
insert into answer_transposition values (7, 'down a perfect 5th', 'XOOXX');
insert into answer_transposition values (8, 'down a major 3rd', 'OOXXO');
insert into answer_transposition values (9, 'up a major 3rd', 'OOXXX');
insert into answer_transposition values (10, 'up a major 2nd', 'XOXXO');
insert into answer_transposition values (11, 'down a perfect 5th', 'OOXXX');
insert into answer_transposition values (12, 'down a major 2nd', 'OOXOX');
insert into answer_transposition values (13, 'up a major 3rd', 'XOXXX');
insert into answer_transposition values (14, 'up a perfect 5th', 'XOOXX');
insert into answer_transposition values (15, 'down a major 2nd', 'XOOXX');